[package]
name = "chip_8_emulator"
version = "0.1.0"
authors = ["stan <knezes1@unlv.nevada.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
ggez = "0.5"